"""Resume the 8-deck tournament: 17 pairs already completed (hardcoded below from
the earlier run), so only run the remaining 11 pairs, then write the full report.
Hang-proofed (max_steps cap). Reuses ROSTER/META/_build from exp_tournament.

Run:  python scripts/exp_tournament_resume.py
"""
from __future__ import annotations
import os, sys, time
from concurrent.futures import ProcessPoolExecutor

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import exp_tournament as T  # ROSTER, META, _build

# 17 pairs already played (dA, dB, winsA, winsB) from the earlier n=240 run.
PRECOMPUTED = [
    ("fighting_pivot", "single_prize_control", 132, 108),
    ("fighting_pivot", "mega_starmie_ex_2", 38, 202),
    ("fighting_pivot", "starmie_aggro", 77, 163),
    ("fighting_pivot", "dragapult_dusknoir", 157, 83),
    ("fighting_pivot", "ns_zoroark_toolbox", 178, 62),
    ("fighting_pivot", "lightning_counter", 224, 16),
    ("fighting_pivot", "mega_starmie_ex", 33, 207),
    ("single_prize_control", "mega_starmie_ex_2", 62, 178),
    ("single_prize_control", "starmie_aggro", 62, 178),
    ("single_prize_control", "dragapult_dusknoir", 149, 90),
    ("single_prize_control", "ns_zoroark_toolbox", 139, 101),
    ("single_prize_control", "lightning_counter", 119, 118),
    ("single_prize_control", "mega_starmie_ex", 15, 225),
    ("mega_starmie_ex_2", "starmie_aggro", 177, 63),
    ("mega_starmie_ex_2", "dragapult_dusknoir", 228, 12),
    ("mega_starmie_ex_2", "ns_zoroark_toolbox", 212, 28),
    ("mega_starmie_ex_2", "lightning_counter", 202, 37),
]
# 11 remaining pairs to compute.
REMAINING = [
    ("mega_starmie_ex_2", "mega_starmie_ex"),
    ("starmie_aggro", "dragapult_dusknoir"),
    ("starmie_aggro", "ns_zoroark_toolbox"),
    ("starmie_aggro", "lightning_counter"),
    ("starmie_aggro", "mega_starmie_ex"),
    ("dragapult_dusknoir", "ns_zoroark_toolbox"),
    ("dragapult_dusknoir", "lightning_counter"),
    ("dragapult_dusknoir", "mega_starmie_ex"),
    ("ns_zoroark_toolbox", "lightning_counter"),
    ("ns_zoroark_toolbox", "mega_starmie_ex"),
    ("lightning_counter", "mega_starmie_ex"),
]


def _chunk(args):
    dA, dB, n, seed = args
    import random
    import engine  # noqa: F401
    from engine.harness import play_match
    random.seed(seed)
    a, deckA = T._build(dA, seed)
    b, deckB = T._build(dB, seed + 10_000)
    res = play_match(a, b, deckA, deckB, n_games=n, max_steps=4000)
    return res["wins_a"], res["wins_b"]


def main():
    decks = list(T.ROSTER)
    win = {a: {b: 0 for b in decks} for a in decks}
    dec = {a: {b: 0 for b in decks} for a in decks}

    def record(dA, dB, wa, wb):
        win[dA][dB] += wa; win[dB][dA] += wb
        dec[dA][dB] += wa + wb; dec[dB][dA] += wa + wb

    for dA, dB, wa, wb in PRECOMPUTED:
        record(dA, dB, wa, wb)

    print(f"resuming: {len(PRECOMPUTED)} pairs precomputed, {len(REMAINING)} to run")
    with ProcessPoolExecutor(max_workers=10) as ex:
        for dA, dB in REMAINING:
            t0 = time.perf_counter()
            jobs, remaining, k = [], 240, 0
            while remaining > 0:
                c = min(12, remaining)
                jobs.append((dA, dB, c, 100 + k)); remaining -= c; k += 1
            futs = [ex.submit(_chunk, j) for j in jobs]
            wa = wb = 0
            for fut in futs:
                try:
                    r = fut.result(timeout=480); wa += r[0]; wb += r[1]
                except Exception:
                    pass
            record(dA, dB, wa, wb)
            wr = wa / (wa + wb) if (wa + wb) else 0
            print(f"  {dA:<20} vs {dB:<20} {wr:>5.0%} ({wa}-{wb}) [{time.perf_counter()-t0:.0f}s]")

    # ----- ranking + report (same format as exp_tournament) -----
    rank = []
    for a in decks:
        tw = sum(win[a][b] for b in decks if b != a)
        td = sum(dec[a][b] for b in decks if b != a)
        rank.append((a, tw / td if td else 0.0, tw, td))
    rank.sort(key=lambda r: -r[1])

    L = ["# 8-Deck Round-Robin Tournament\n",
         "_Generated by `scripts/exp_tournament_resume.py` — 240 games per pair, 8 decks, 28 matchups._\n",
         "Every deck is piloted by the **same search agent** (`SearchTeacher`) at its best per-deck config. "
         "It evaluates **every legal option** each decision and, at 2-ply, scores each by the **opponent's "
         "reply** — so it plays **defensively** (keeps its attacker alive to act again) and plays the "
         "heuristic-invisible **dynamic-damage attacks**. Both sides use the same agent, so results measure "
         "**deck strength + piloting against a peer** — a real-competition proxy, unlike the vs-heuristic "
         "benchmark (which the heuristic mispilots).\n",
         "## Roster (best config + win-rate vs the heuristic)\n",
         "| # | deck | archetype | config | vs heuristic |",
         "|---|------|-----------|--------|--------------|"]
    for i, d in enumerate(decks, 1):
        wh, arch, _ = T.META[d]
        whs = f"{wh:.1f}%" if wh is not None else "n/a"
        L.append(f"| {i} | `{d}` | {arch} | {T.ROSTER[d]['plies']}-ply | {whs} |")
    L.append("")
    short = {d: d.replace("_", " ")[:13] for d in decks}
    L.append("## Win-rate matrix (row deck's win% vs column deck)\n")
    L.append("| vs → | " + " | ".join(short[d] for d in decks) + " |")
    L.append("|------|" + "|".join("---" for _ in decks) + "|")
    for a in decks:
        cells = []
        for b in decks:
            if a == b:
                cells.append(" — ")
            else:
                d = dec[a][b]
                cells.append(f"{(win[a][b]/d*100 if d else 0):.0f}%")
        L.append(f"| **{short[a]}** | " + " | ".join(cells) + " |")
    L.append("")
    L.append("## Overall ranking (win% vs the whole field)\n")
    L.append("| rank | deck | win% vs field | record |")
    L.append("|------|------|---------------|--------|")
    for i, (a, wr, tw, td) in enumerate(rank, 1):
        L.append(f"| {i} | `{a}` | **{wr:.1%}** | {tw}/{td} |")
    L.append("")
    L.append("## Per-deck strategy\n")
    for a, wr, tw, td in rank:
        wh, arch, strat = T.META[a]
        whs = f"{wh:.1f}% vs heuristic" if wh is not None else ""
        L.append(f"### {a} — {arch}")
        L.append(f"_Field win-rate: **{wr:.1%}** · {whs} · {T.ROSTER[a]['plies']}-ply_\n")
        L.append(strat + "\n")
    L.append("## Caveats\n")
    L.append("- Same agent both sides → isolates **deck** strength; not the Kaggle ladder.")
    L.append("- vs-heuristic win-rates are inflated by the heuristic **mispiloting** these decks; the field "
             "win-rates here are the fairer skill-neutral comparison.")
    L.append("- Combo decks (Dragapult, Zoroark) are slowest to set up, so fast aggro out-races them here.")

    out = "tournaments/8_deck_tourney.md"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write("\n".join(L))
    print(f"\nWrote {out}\n=== FINAL RANKING ===")
    for i, (a, wr, tw, td) in enumerate(rank, 1):
        print(f"  {i}. {a:<22} {wr:.1%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
