"""Use Sakana (fugu-ultra reasoning) to GENERATE diverse, strategy-driven decks.

Each deck is designed around a distinct strategic brief (matchups / weakness-vs-
strength / card optimization), then legalized + validated in the engine. The
rationale (concept, strategy, key cards, matchups, consistency) is written to
docs/DECK_STRATEGY.md so it directly addresses the competition judging criteria.

Run with the conda env's python (slow — reasoning calls):
  C:/Users/itach/miniconda3/envs/pokemon_tcg/python.exe scripts/sakana_design_decks.py
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from dotenv import load_dotenv  # noqa: E402

load_dotenv(os.path.join(REPO, ".env"))

import engine  # noqa: E402,F401
from cg.api import CardType  # noqa: E402
from cg.game import battle_finish, battle_start  # noqa: E402
from engine.cards import get_card_db  # noqa: E402
from engine.decks import legalize_deck  # noqa: E402
from llm.providers.sakana_agent import SakanaProvider  # noqa: E402

DIGEST = open(os.path.join(REPO, "data", "card_digest.md"), encoding="utf-8").read()

JUDGING = (
    "Your design is judged on: (a) clear articulation of the approach + rationale; "
    "(b) originality + technical soundness; (c) consistency under repeated matches; "
    "(d) robustness (avoid over-reliance on specific openings/matchups/situational luck); "
    "(e) competition performance; (f) a clear deck concept aligned with the strategy; "
    "(g) effective key-card selection + utilization for the game plan. Address these."
)

RULES = (
    "Hard rules: exactly 60 cards; at most 4 copies of any card except Basic Energy "
    "([1]Grass [2]Fire [3]Water [4]Lightning [5]Psychic [6]Fighting [7]Darkness [8]Metal, unlimited); "
    "at most 1 ACE SPEC; include pre-evolutions for any Stage 1/2 (or Rare Candy + the Basic); "
    "energy must match attacker costs. Use ONLY card IDs that appear in the digest."
)

BRIEFS = [
    ("lightning_counter",
     "The ladder META is Water (Mega Starmie ex). Water Pokemon are WEAK to Lightning {L}. "
     "Design a fast, consistent LIGHTNING aggro deck that exploits this weakness to one-shot Water "
     "attackers, with a deep search/draw engine so it opens reliably."),
    ("consistent_control",
     "Design a LOW-VARIANCE control/disruption deck that minimizes reliance on lucky openings: deep "
     "search, energy denial (Crushing/Enhanced Hammer), item/supporter lock, recursion, and a resilient "
     "attacker. Prioritize CONSISTENCY and ROBUSTNESS across matchups."),
    ("original_tech",
     "Design an ORIGINAL, technically-sound OFF-META deck with a clever but reliable game plan the Water "
     "meta is unprepared for. Explain the novel idea and why it is robust, not gimmicky."),
]

OUT_FMT = (
    'Output ONLY a JSON object (no prose around it) with keys: '
    '"name" (short slug), "concept" (1-2 sentences), "strategy" (the game plan), '
    '"key_cards" (array of "Nx Name [id] - why"), "matchups" (weakness/resistance exploitation; what it '
    'beats/loses to), "consistency" (how it stays consistent and robust), '
    '"cards" (array of [count, card_id] pairs that sum to 60).'
)


def parse_json(text):
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except Exception:
        return None


def to_card_list(cards_field):
    flat = []
    for item in cards_field or []:
        if isinstance(item, (list, tuple)) and len(item) >= 2:
            cnt, cid = int(item[0]), int(item[1])
        elif isinstance(item, dict):
            cnt, cid = int(item.get("count", 1)), int(item.get("id") or item.get("card_id"))
        else:
            continue
        flat += [cid] * cnt
    return flat


def deck_legal(deck):
    try:
        obs, sd = battle_start(deck, deck)
    except Exception:
        return False
    ok = obs is not None and getattr(sd, "errorPlayer", 0) < 0
    try:
        battle_finish()
    except Exception:
        pass
    return ok


def stats(deck, db):
    basics = sum(1 for c in deck if db.card(c) and int(db.card(c).cardType) == CardType.POKEMON and db.card(c).basic)
    energy = sum(1 for c in deck if db.card(c) and int(db.card(c).cardType) in (5, 6))
    return basics, energy


def main() -> int:
    db = get_card_db()
    provider = SakanaProvider(model="fugu-ultra", max_tokens=2600)
    doc = ["# Deck strategies (designed by Sakana fugu-ultra)\n",
           "Each deck below was generated by a reasoning model around a distinct strategic brief, then "
           "legalized + validated in the engine. Rationale is written to address the competition judging "
           "criteria (articulation, originality, consistency, robustness, performance, concept clarity, "
           "key-card utilization).\n"]
    results = []
    for key, brief in BRIEFS:
        print(f"\n=== Designing '{key}' with Sakana fugu-ultra ... ===")
        system = ("You are a world-class competitive Pokemon TCG deckbuilder and strategist. "
                  + JUDGING)
        user = (f"BRIEF: {brief}\n\n{RULES}\n\n{OUT_FMT}\n\n"
                f"CARD POOL DIGEST:\n{DIGEST}")
        try:
            raw = provider.complete(system, user)
        except Exception as e:
            print(f"  FAIL: {type(e).__name__}: {str(e)[:120]}")
            continue
        data = parse_json(raw)
        if not data:
            print("  could not parse JSON from Sakana response")
            continue
        flat = to_card_list(data.get("cards"))
        legal_list = legalize_deck(flat, db)
        legal = deck_legal(legal_list)
        basics, energy = stats(legal_list, db)
        path = os.path.join(REPO, "decks", f"sakana_{key}.csv")
        with open(path, "w") as f:
            f.write("\n".join(str(x) for x in legal_list) + "\n")
        print(f"  {data.get('name', key)}: legal={legal} basics={basics} energy={energy} "
              f"(raw {len(flat)} cards -> legalized 60) -> decks/sakana_{key}.csv")
        results.append((key, data, legal, basics, energy))

        doc.append(f"\n## sakana_{key} — {data.get('name', key)}  "
                   f"(legal={legal}, basics={basics}, energy={energy})")
        doc.append(f"**Concept:** {data.get('concept', '')}")
        doc.append(f"**Strategy:** {data.get('strategy', '')}")
        doc.append(f"**Matchups:** {data.get('matchups', '')}")
        doc.append(f"**Consistency / robustness:** {data.get('consistency', '')}")
        kc = data.get("key_cards", [])
        doc.append("**Key cards:** " + ("; ".join(kc) if isinstance(kc, list) else str(kc)))

    with open(os.path.join(REPO, "docs", "DECK_STRATEGY.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(doc) + "\n")
    print(f"\n=== Done: {sum(1 for r in results if r[2])}/{len(results)} legal. "
          f"Rationale -> docs/DECK_STRATEGY.md ===")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
